### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [LibraryCarpentry/lc-git#50]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided => [yes](https://librarycarpentry.org/lc-git/guide/), but: #32 cc @drjwbaker
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by katrinleinweber** [comment]
My primary focus is https://github.com/swcarpentry/r-novice-inflammation/issues/415, so I can't promise to participate here more than the 5 items I checked just now, I'm sorry.

**Comment by ErinBecker** [comment]
Thanks @katrinleinweber for your work on this and for letting us know. Hopefully your co-Maintainers can continue the work here.

**Comment by libcce** [comment]
@katrinleinweber @ErinBecker The lesson has been taught many times and is actually stable so we can release it. We've collected feedback that does need to be incorporated after the release. @EvaSeidlmayer @dheles @tpatwood do you want to look into the additional items on the checklist? I will help with some. Thanks @katrinleinweber for moving this forward.

**Comment by ErinBecker** [comment]
Thanks @libcce - We'll be putting out a blog post and some tweets on the 15th to invite community contributions for lessons that are working towards the June release. Contributors will be pointed towards the "June 2019 Release" milestone, so please assign any issues you would like community help with to that milestone. Please let me know if you have any questions or need help with technical / lesson rendering issues. Looking forward to the release!

**Comment by libcce** [comment]
I've checked off **Lesson links work as expected**. There are two pull requests https://github.com/LibraryCarpentry/lc-git/pull/56 and https://github.com/LibraryCarpentry/lc-git/pull/57 that fix the remaining link issues.

**Comment by tpatwood** [comment]
I can try making sure setup instructions is all set, and I'll try to go through the exercises to make sure they run as expected (#s 1, 2, and 3). I am not entirely sure what is meant by the file structure item? Is this for lessons that require a downloaded package?

**Comment by tpatwood** [comment]
Oh! And to be clear, should these be done *by*  18 June 2019 or before?

**Comment by libcce** [comment]
@tpatwood for the file structure item it looks like this lesson has a fig folder which is different from what I've seen in other lessons. Other lessons have used the assets folder and the img folder. @ErinBecker what would you recommend here? Otherwise, everything else checks out.

**Comment by libcce** [comment]
@tpatwood from @ErinBecker's message via TopicBox, we have until June 3rd to complete the checklist.

**Comment by libcce** [comment]
I can't find anything wrong with the file structure so I'm checking it off. @tpatwood if you want to double check? But I think we are finished.

**Comment by ErinBecker** [comment]
Awesome work @silviadg87 @libcce @tpatwood @elopatin-uc3 @dheles @EvaSeidlmayer and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3265772
